[package]
name = "ranabi"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
colored = "2.0.4"
indexmap = "2.1.0"
itertools = "0.11.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
